server:
  port: 8080

session:
  store-type: redis
  timeout: 3600

spring: 
  application: 
    name: yyskt
  datasource:
    url: jdbc:mysql://localhost:3306/yueyang?serverTimezone=UTC
    username: root
    password: abc1176478896
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.6
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis:
  mapper-locations: classpath:mapper/**/*.xml    # mapper映射文件位置
  type-aliases-package: com.yyskt.entity    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true #下划线转驼峰

logging: 
  config: classpath:logback-spring.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
